### ISSUE TITLE
Error loading Cache Table Invalid Load Key 

### ISSUE THREAD

**Issue by mindsailor** [theovercomer8/captionr#8]
I opened a couple of different colabs accounts today both with different zips, and both after a couple of runtime restarts were still exhibiting this behavior from the stock colab link on github.

Was hoping you may be able to offer insight. Thank you!  

![Error](https://user-images.githubusercontent.com/24350726/219905464-ca870645-4639-4256-8a0e-9eb9717ad2a4.png)

**Comment by theovercomer8** [comment]
Sorry I broke some dependencies earlier. It should be fixed now.

**Comment by mindsailor** [comment]
I tried a few times I got original error and also

Traceback (most recent call last):
  File "/content/captionr/captionr/captionr_class.py", line 251, in process_img
    dirname = os.path.dirname(cap_file) if config.output == '' or config.output is None else str(config.output[0])
TypeError: 'PosixPath' object is not subscriptable


not sure it's related but I see this error in dependencies

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.

**Comment by samp3209** [comment]
I'm also running into the same problem at mindsailor with the posixpath issue. I think that issue has something to do with the output directory location.

**Comment by mindsailor** [comment]
Ran error through GPT and it told me to replace 
/content/captionr/captionr/captionr_class.py
Line 251 with
dirname = os.path.dirname(cap_file) if config.output == '' or config.output is None else (list(config.output)[0] if isinstance(config.output, (list, tuple)) else config.output)

I still got key errors however once this past captions began as normal.

 ERROR:root:Error loading cached table artists: invalid load key, 'E'.
ERROR:root:Error loading cached table mediums: invalid load key, 'E'.
ERROR:root:Error loading cached table movements: invalid load key, 'E'.
ERROR:root:Error loading cached table trendings: invalid load key, 'E'.

**Comment by theovercomer8** [comment]
I think the first cache table issue is related to an out of date notebook. Can you verify you're on the latest revision in Colab by going to File->Revision History and making sure the right column has the top-most revision selected:
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/122644869/219973347-3ce02828-f362-4cc2-84e4-97aad8bcb671.png">

As far as the other issue you both had, can you get latest and see if its resolved?

**Comment by samp3209** [comment]
Looks like the issue with the Posix Path was fixed with newest colab. Thanks!

**Comment by mindsailor** [comment]
Posix error is fixed here as well. Thank you!
